version: "3"
services:
  channel:
    build:
      context: .
      dockerfile: channel/Dockerfile
    container_name: "channel"
    environment:
      NATS_URI: nats://nats:4222
    ports:
      - "8005:8005"
    depends_on:
      - nats
  sleep:
    build:
      context: .
      dockerfile: sleep/Dockerfile
    container_name: "sleep"
    environment:
      NATS_URI: nats://nats:4222
    ports:
      - "8006:8006"
    depends_on:
      - nats
  device:
    build:
      context: .
      dockerfile: device/Dockerfile
    container_name: "device"
    environment:
      NATS_URI: nats://nats:4222
      SLEEP_SERVER_URI: sleep:8006
    depends_on:
      - nats
      - sleep
  nats:
    image: nats:2.1.8
    ports:
    - 4222:4222
    - 8222:8222
