version: "3"
services:
  nats-streaming:
    image: nats-streaming
    ports:
    - 4222:4222
    - 8222:8222
    command:
      - "--store"
      - file
      - "--dir"
      - /data/msg
      - "--max_msgs"
      - "0"
      - "--max_bytes"
      - "0"
      - "-ma"
      - "10m"
    volumes:
      - "./data:/data"
